baseURL: "https://dolacz.zsp.net.pl"
languageCode: "pl-pl"
title: "Bądź bezpieczniejszy, bądź zorganizowany! Dołącz do ZSP!"
description: "ZSP - oddolna organizacja pracownicza, walczmy o swoje prawa! Poznaj nas, i dołącz do nas :-)"
theme: "dolacz-zsp-net-pl"

# common
step_statut: &step_statut
    title: Ogólne zasady i statut
    text: Zapoznaj się z naszymi najważniejszymi zasadami, oraz ze statutem funkcjonowania organizacji<br/><br/><a href="https://zsp.net.pl/statut" target="_blank" class="important-link"><img src="images/icons/ok-hand.png" class="link-image"> Zobacz statut</a>

step_organization_form: &step_organization_form
    title: Wybór typu związku
    text: W zależności od potrzeb wybierz formę organizacyjną.<br/><br/>- <strong>Związek regionalny</strong>, aby komunikować się między branżami i sobie pomagać wzajemnie (taka forma jest u nas najpopularniejsza)<br/>- <strong>Związek branżowy</strong>, aby działać silnie w konkretnej branży na zasadzie pomocy wzajemnej i zachęcać do tworzenia związków zawodowych na zakładach<br/>- <strong>Związek zakładowy (związek zawodowy)</strong> - formalna organizacja związkowa w miejscu pracy

step_contact: &step_contact
    title: Masz dodatkowe pytania?
    text: Odezwij się do nas bezpośrednio, kontakt do nas znajdziesz na samym dole tej strony - w stopce :-)


params:
    keywords: "założyć związek zawodowy, związki zawodowe, przystąpić do związku, zsp, związek syndykalistów polski, organizacja pracownicza, obrona praw pracowników, kodeks pracy, walka pracownicza, syndykalizm, anarchosyndykalizm, umowa zlecenie, umowa o pracę, umowa o dzieło, zoganizuj się, umowy śmieciowe"
    front_title: "Solidarność! Pomoc wzajemna! Dołącz do nas!"

    join_us:
        - title: "> Chcę dołączyć do istniejącej organizacji związkowej ZSP wypisanej powyżej"
          engagement: member-organizer,member
          steps:
              - <<: *step_statut
              - <<: *step_organization_form

              - title: Zdecydowany/zdecydowana? Wypełnij i złóż ankietę członkowską online!"
                text: "To nic trudnego! Wypełnij naszą ankietę członkowską zostawiając kontakt do siebie, a nasi członkowie się do Ciebie odezwą! <br/><br/><a href=\"\" data-adr=\"aHR0cHM6Ly9mb3JtLmRvbGFjei56c3AubmV0LnBsL2Fua2lldGEtY3psb25rYQ==\" target=\"_blank\" rel=\"nofollow\" class=\"important-link\"><img src=\"images/icons/ok-hand.png\" class=\"link-image\"> <strong>Wypełnij i złóż ankietę</strong></a>"

              - title: Zaproszenie na spotkanie
                text: Przyjdź na spotkanie lub dołącz do spotkania online, które zorganizują nasi członkowie. Zostaniesz na nie zaproszony/a.

              - title: Wprowadzenie
                text: "Koniecznie zapoznaj się z naszym \"Pakietem startowym\" <br/><br/><a href=\"\" data-adr=\"aHR0cHM6Ly9mb3JtLmRvbGFjei56c3AubmV0LnBsL3Bha2lldC1zdGFydG93eQ==\" target=\"_blank\" rel=\"nofollow\" class=\"important-link\"><img src=\"images/icons/ok-hand.png\" class=\"link-image\"> <strong>Zobacz \"pakiet startowy\"</strong></a>"

              - title: Głosowanie nad przyjęciem
                text: W zależności od lokalnej grupy, do której chcesz się zapisać przyjęcie na członka może być na pierwszym lub na innym kolejnym spotkaniu. Wszyscy członkowie lokalnej grupy będą musieli zagłosować - obowiązuje demokracja bezpośrednia.

              - <<: *step_contact

        - title: "> Jestem z innego miasta i innej branży, chcę założyć nowy związek"
          engagement: member-organizer,member
          steps:
              - <<: *step_statut
              - <<: *step_organization_form

              - title: Wypełnij ankietę członkowską online
                text: "To nic trudnego! Wypełnij naszą ankietę członkowską online, zostaw do siebie kontakt, skontaktujemy się z Tobą. Jeżeli w Twojej branży lub lokalizacji nie ma aktywnego związku to wspólnie opracujemy plan utworzenia nowego związku.<br/><br/><a href=\"\" data-adr=\"aHR0cHM6Ly9mb3JtLmRvbGFjei56c3AubmV0LnBsL3duaW9zZWstby11dHdvcnplbmllLXNla2NqaQ==\" target=\"_blank\" rel=\"nofollow\" class=\"important-link\"><img src=\"images/icons/ok-hand.png\" class=\"link-image\"> <strong>Wypełnij i złóż wniosek</strong></a>"

              - title: Porozmawiajmy
                text: Odezwiemy się do Ciebie tak szybko, jak tylko damy radę aby ustalić co możemy w danej chwili zrobić

              - title: Status grupy inicjatywnej
                text: Według naszego statutu 2 osoby są potrzebne do założenia tzw. "grupy inicjatywnej" regionalnej, oraz 1 osobę w przypadku zakładu pracy.

              - title: Szkolenie
                text: "Nasi członkowie zorganizują szkolenie u Ciebie lub u nas. Koniecznie zapoznaj się z pakietem startowym.<br/><br/><a href=\"\" data-adr=\"aHR0cHM6Ly9mb3JtLmRvbGFjei56c3AubmV0LnBsL3Bha2lldC1zdGFydG93eQ==\" target=\"_blank\" rel=\"nofollow\" class=\"important-link\"><img src=\"images/icons/ok-hand.png\" class=\"link-image\"> <strong>Zobacz \"pakiet startowy\"</strong></a>"

              - title: Głosowanie nad przyjęciem
                text: Na szczeblu krajowym zostanie zorganizowane referendum, w którym wszystkie związki ZSP muszą podjąć uchwałę o przyjęciu grupy inicjatywnej jako związku ZSP

              - <<: *step_contact

        - title: "> Chcę zostać sympatykiem/sympatyczką"
          engagement: sympathetic
          steps:
              - title: Wypełnij ankietę sympatyka!
                text: "Odpowiedz na kilka pytań, abyśmy mogli się lepiej poznać <br/><br/><a href=\"\" data-adr=\"aHR0cHM6Ly9mb3JtLmRvbGFjei56c3AubmV0LnBsL2Fua2lldGEtc3ltcGF0eWth\" target=\"_blank\" rel=\"nofollow\" class=\"important-link\"><img src=\"images/icons/ok-hand.png\" class=\"link-image\"> <strong>Wypełnij i złóż ankietę!</strong></a>"

              - title: Skontaktujemy się z Tobą
                text: W zależności od wyborów w ankiecie będziemy mogli dodać Cię np. do odpowiedniej grupy na facebooku

              - <<: *step_contact

    engagement:
        tabs:
            - name: sympathetic
              title: Będę sympatykiem(czką)!
              selected: false
              text: >
                Nie mam możliwości regularnie uczestniczyć, ale mogę od czasu do czasu wykonywać któreś z czynności według moich możliwości:<br/><br/>
                - Udzielać porad prawnych<br/>
                - Przygotowywać grafiki pod plakaty, ulotki, infografiki, strony WWW<br/>
                - Przyjść na pikietę, demonstrację<br/>
                - Rozkleić plakaty<br/>
                - Rozdać ulotki<br/>
                - Promować posty w social media<br/>
                - Skierować kogoś, kto potrzebuje pomocy lub chce utworzyć związek na zakładzie

            - name: member
              title: Chcę być członkiem/członkinią!
              selected: true
              text: >
                  Według możliwości, każdemu według potrzeb - członek nie ma obowiązku robienia wszystkiego, może poruszać się w obszarze, w którym dobrze się czuje.<br/><br/>
                  - Będę brać udział w głosowaniach<br/>
                  - Według możliwości chcę uczestniczyć w spotkaniach lokalnej grupy<br/>
                  - Od czasu do czasu lub częściej coś zaproponuję od siebie<br/>
                  - Przyjdę na wydarzenia, czasem mogę pomóc w organizowaniu lub sam/sama zorganizuję<br/>
                  - Można mnie wybrać na skarbnika lub sekretarza &nbsp;<i><small>(jeżeli zgłoszę kandydaturę)</small></i><br/>
                  - Będę prowadzić sprawy pracownicze lub pomagać je rozwiązywać &nbsp;<i><small>(jeśli się podejmę tego)</small></i><br/>
                  - Mogę kontaktować się z mediami &nbsp;<i><small>(jeśli się zgłoszę do tego)</small></i><br/>
                  - Napiszę artykuł od czasu do czasu &nbsp;<i><small>(jeśli się zgłoszę do tego)</small></i>
