baseURL: "https://stage.dolacz.zsp.net.pl"
languageCode: "pl-pl"
title: "Bądź bezpieczniejszy, bądź zorganizowany! Dołącz do ZSP!"
description: "ZSP - oddolna organizacja pracownicza, walczmy o swoje prawa! Poznaj nas, i dołącz do nas :-)"
theme: "dolacz-zsp-net-pl"

# common
step_statut: &step_statut
    title: Ogólne zasady i statut
    text: Zapoznaj się z naszymi najważniejszymi zasadami, oraz ze statutem funkcjonowania organizacji<br/><br/><a href="https://zsp.net.pl/statut" target="_blank"><img src="images/icons/ok-hand.png" class="link-image"> Zobacz statut</a>

step_organization_form: &step_organization_form
    title: Wybór typu sekcji
    text: W zależności od potrzeb wybierz formę organizacyjną.<br/><br/>- <strong>Sekcja regionalna</strong>, aby komunikować się między branżami i sobie pomagać wzajemnie (taka forma jest u nas najpopularniejsza)<br/>- <strong>Sekcja branżowa</strong>, aby działać silnie w konkretnej branży na zasadzie pomocy wzajemnej i zachęcać do tworzenia związków zawodowych na zakładach<br/>- <strong>Związek zawodowy</strong> - formalna organizacja związkowa w miejscu pracy

step_contact: &step_contact
    title: Masz dodatkowe pytania?
    text: Odezwij się do nas bezpośrednio, kontakt do nas znajdziesz na samym dole tej strony - w stopce :-)


params:
    keywords: "założyć związek zawodowy, związki zawodowe, przystąpić do związku, zsp, związek syndykalistów polski, organizacja pracownicza, obrona praw pracowników, kodeks pracy, walka pracownicza, syndykalizm, anarchosyndykalizm, umowa zlecenie, umowa o pracę, umowa o dzieło, zoganizuj się, umowy śmieciowe"
    front_title: "Solidarność! Pomoc wzajemna! Dołącz do nas!"

    join_us:
        - title: "> Chcę dołączyć do istniejącej sekcji ZSP wypisanej powyżej"
          engagement: member-organizer,member
          steps:
              - <<: *step_statut
              - <<: *step_organization_form

              - title: Zdecydowany/zdecydowana? Wypełnij i złóż ankietę członkowską online!
                text: "Wypełnij naszą ankietę członkowską zostawiając kontakt do siebie, a nasi członkowie się do Ciebie odezwą! // @TODO: DODAĆ LINKA"

              - title: Zaproszenie na spotkanie
                text: Przyjdź na spotkanie lub dołącz do spotkania online, które zorganizują nasi członkowie. Zostaniesz na nie zaproszony/a.

              - title: Głosowanie nad przyjęciem
                text: W zależności od lokalnej grupy, do której chcesz się zapisać przyjęcie na członka może być na pierwszym lub na innym kolejnym spotkaniu. Wszyscy członkowie lokalnej grupy będą musieli zagłosować - obowiązuje demokracja bezpośrednia.

              - <<: *step_contact

        - title: "> Jestem z innego miasta i innej branży, chcę założyć nową sekcję"
          engagement: member-organizer,member
          steps:
              - <<: *step_statut
              - <<: *step_organization_form

              - title: Wypełnij wniosek o zapotrzebowanie na nową sekcję
                text: "Wniosek zostanie rozpatrzony przez nas m.in. w kontekście tego, czy jest wystarczająca liczba chętnych ludzi aby według statutu utworzyć sekcję // @TODO LINK"

              - title: Porozmawiajmy
                text: Odezwiemy się do Ciebie tak szybko, jak tylko damy radę aby ustalić co możemy w danej chwili zrobić

              - title: Szkolenie
                text: Nasi członkowie zorganizują szkolenie u Ciebie lub u nas. Dostaniesz materiały szkoleniowe oraz "pakiet startowy" z narzędziami ułatwiającymi pracę w swojej sekcji.

              - title: Głosowanie nad przyjęciem
                text: Na szczeblu krajowym zostanie zorganizowane referendum, w którym wszystkie sekcje ZSP muszą podjąć uchwałę o przyjęciu nowej sekcji

              - <<: *step_contact

        - title: "> Chcę zostać sympatykiem/sympatyczką"
          engagement: sympathetic
          steps:
              - title: Wypełnij ankietę sympatyka!
                text: Odpowiedz na kilka pytań, abyśmy mogli się lepiej poznać

              - title: Skontaktujemy się z Tobą
                text: W zależności od wyborów w ankiecie będziemy mogli dodać Cię np. do odpowiedniej grupy na facebooku

              - <<: *step_contact

        - title: "> Chcę pomagać przy konkretnych pracach jako konsultant"
          engagement: consultant
          steps:
              - title: Wypełnij ankietę konsultanta!
                text: Odpowiedz nam na kilka pytań, dzięki którym będziemy mogli się lepiej poznać i m.in. dodać Cię do odpowiedniej grupy na facebooku

              - <<: *step_contact

    engagement:
        tabs:
            - name: sympathetic
              title: Będę sympatykiem(czką)!
              selected: false
              text: >
                  Nie mam możliwości aktywnie uczestniczyć, ale mogę od czasu do czasu wykonywać któreś z czynności:<br/><br/>
                  - Przyjść na pikietę, demonstrację<br/>
                  - Rozkleić plakaty<br/>
                  - Rozdać ulotki<br/>
                  - Promować posty w social media<br/>
                  - Skierować kogoś, kto potrzebuje pomocy lub chce utworzyć związek na zakładzie

            - name: consultant
              title: Chcę pomagać<br/> jako konsultant(ka)!
              text: Nie mam możliwości aktywnie uczestniczyć, ale chętnie będę w kontakcie aby według moich możliwości pomóc przy jednej lub więcej z tych czynności:<br/><br/>- Wykonywanie grafik np. plakatów, ulotek, bannerów, grafik www, infografik na social media<br/>- Porady prawne<br/>- Promocja postów w social media
              selected: false

            - name: member
              title: Chcę uczestniczyć!
              selected: true
              text: >
                  - Będę brać udział w głosowaniach<br/>
                  - Według możliwości chcę uczestniczyć w spotkaniach lokalnej grupy<br/>
                  - Od czasu do czasu lub częściej coś zaproponuję od siebie<br/>
                  - Przyjdę na wydarzenia, czasem mogę pomóc w organizowaniu<br/>

            - name: member-organizer
              title: Będę organizatorem(ką)!
              selected: false
              text: >
                - Od czasu do czasu lub częściej zaproponuję nowy bądź podchwycę istniejący temat, pociągnę go do przodu<br/>
                - Zoorganizuję pikietę, demonstrację, spotkanie otwarte lub inną inicjatywę<br/>
                - Będę regularnie uczęszczać na spotkania<br/>
                - Mogę pełnić jakąś funkcję np. skarbnika/skarbniczki czy sekretarza/sekretarki
